version: '3'
services:
  myapi:
    build: .
    ports:
      - "5000:5000"
    environment:
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_DB: mydatabase
      MONGO_USER: myuser
      MONGO_PASS: mypassword
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: myuser
      MONGO_INITDB_ROOT_PASSWORD: mypassword
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:
