name: Automatic Docker Image Publish

on:
  push:
    branches:
      - main
jobs:
  build-and-publish-automatic:
    name: Build and Publish Docker Image (Automatic)
    if: |
      github.event_name == 'push' &&
      contains(github.event.head_commit.message, 'Version')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get Version Tag
        run: echo "::set-output name=version::$(echo ${{ github.event.head_commit.message }} | grep -oP '(?i)version\s*:?\s*\K\d+(\.\d+)+')"
        run: echo ${{ steps.get_version.outputs.version }}

      - name: Login to GitHub Container Registry
        run: echo ${{ secrets.DOCKERUHUB_SECRET }} | docker login -u ghvinerias --password-stdin

      - name: Build Docker Image
        run: docker build -t ghvinerias/pyapi:${{ steps.get_version.outputs.version }} .

      - name: Publish Docker Image to GitHub Container Registry
        run: docker push ghvinerias/pyapi:${{ steps.get_version.outputs.version }}
