name: Manual Docker Image Publish

on:
  workflow_dispatch:

jobs:
  build-and-publish:
    name: Build and Publish Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get Docker Image Tag
        id: input_tag
        run: |
          echo "::set-output name=tag::$(read -p 'Enter Docker Image Tag: ' tag && echo $tag)"

      - name: Login to GitHub Container Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: Build Docker Image
        run: docker build -t ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:${{ steps.input_tag.outputs.tag }} .

      - name: Publish Docker Image to GitHub Container Registry
        run: docker push ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:${{ steps.input_tag.outputs.tag }}
